### ISSUE TITLE
Review social media usage and documentation

### ISSUE THREAD

**Issue by amaliacardenas** [codebar/barcelona#99]
Review social media usage and documentation (anyone has any suggestion on this? specially around instagram)

## Description 

We need to create a strategy around how we want to use social media during covid times. 

## Scope

- [ ] What is the purpose that we want to accomplish with the social media accounts?
- [ ] What social media accounts do we keep active?
- [ ] Documentation for the accounts we decide to keep open.

**Comment by saljuama** [comment]
perhaps this issue is also related to this one? https://github.com/codebar/barcelona/issues/55

**Comment by saljuama** [comment]
@Klarala13  to talk to @stefi23  and @KimberleyCook 
@amaliacardenas  to be there to support
@saljuama  has agreed to bribe @stefi23  with programming lessons in exchange for social media knowledge

**Comment by Klarala13** [comment]
@amaliacardenas, @KimberleyCook and @Klarala13 met to see how we can use social media

- Meet with local organizations to do lives on instagram, doing QA sessions.
- Create stories on instagram asking users questions/polls. 
-We decide to work on one platform (at least for now) and document it and start to learn from it. We are thinking about starting with linkedIn. 

@amaliacardenas will document herself a bit on how to create stories and some content. She will also ask @KimberleyCook how to create a linked in account.

**Comment by daverick** [comment]
no advance and it is good!

**Comment by Klarala13** [comment]
no advances and it´s all coooool :)

**Comment by daverick** [comment]
@amaliacardenas just need to push it to the GitHub repo.🎉

**Comment by amaliacardenas** [comment]
@amaliacardenas just need to push it to the GitHub repo.🎉

**Comment by amaliacardenas** [comment]
I added documentation for how to create reels and stories on Instagram. You can find the commit here: https://github.com/codebar/barcelona/commit/e11e018cc28adfb360152ebaeb950e67dc251f3f

**Comment by Klarala13** [comment]
@amaliacardenas pushed the documentation this morning. 
@Klarala13 will post on instagram about our next workshop, start making some noise and review the documentation.

**Comment by Bozena611** [comment]
@Klarala13 posted a few stories on Instagram, we don't know about review.

**Comment by ancagabriela** [comment]
@Klarala13 posted on Instagram last month. When we do presential workshops we can post more.

**Comment by Klarala13** [comment]
It seems like we are posting a bit more frequently on social media so we can close this issue.
